import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Two Column Layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="container mx-auto p-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-white p-6 rounded-lg shadow-md">
              <h2 className="text-2xl font-bold mb-4">Column 1</h2>
              <p className="text-gray-700">
                This is the content for the first column. You can add more
                elements here as needed.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-md">
              <h2 className="text-2xl font-bold mb-4">Column 2</h2>
              <p className="text-gray-700">
                This is the content for the second column. You can add more
                elements here as needed.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
